import { useState } from "react";
import { supabase } from "../lib/supabase";
import { buildVetReportPrompt } from "../lib/vetReport";

export default function VetReport({ cat, predictions, healthLogs }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const hasEnoughData = predictions.length > 0 || healthLogs.length > 0;

  if (!hasEnoughData) {
    return (
      <div className="border-2 border-dashed border-neutral-400 p-4 text-center text-sm text-neutral-500">
        <p className="font-bold">VET REPORT UNAVAILABLE</p>
        <p>Log at least one health entry or prediction to generate a vet report.</p>
      </div>
    );
  }

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const prompt = buildVetReportPrompt(cat, predictions, healthLogs);
      const { data, error: fnError } = await supabase.functions.invoke("gemini-proxy", {
        body: { prompt },
      });
      if (fnError) throw fnError;
      setReport(data.narration);
    } catch (err) {
      setError("Failed to generate report. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const fullText = report
    ? `VET VISIT SUMMARY\nCat: ${cat.name} (${cat.age_category})\nGenerated by Purridiction\n\n${report}`
    : "";

  const handleCopy = () => {
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      <h3 className="font-heading font-black text-lg uppercase tracking-widest">Vet Visit Prep</h3>

      {!report && (
        <button onClick={handleGenerate} disabled={loading}
          className="w-full bg-near-black text-white font-black py-4 border-2 border-near-black hover:bg-neutral-700 disabled:opacity-50 uppercase tracking-widest shadow-[4px_4px_0px_#1A1A2E] hover:shadow-[2px_2px_0px_#1A1A2E] hover:translate-x-[2px] hover:translate-y-[2px] transition-all">
          {loading ? "GENERATING SUMMARY..." : "Generate 7-Day Summary for Vet"}
        </button>
      )}

      {error && (
        <p className="text-red-orange text-sm border-2 border-red-orange p-2 text-center font-bold">{error}</p>
      )}

      {report && (
        <div className="border-4 border-near-black bg-white shadow-[6px_6px_0px_#1A1A2E]">
          {/* Header */}
          <div className="bg-near-black text-white p-4 border-b-4 border-near-black">
            <p className="text-xs font-mono tracking-widest mb-1">PURRIDICTION // VET VISIT PREP</p>
            <p className="text-xl font-black">{cat.name.toUpperCase()}</p>
            <p className="text-xs font-mono text-neutral-400 mt-1">
              7-Day Summary // Generated {new Date().toLocaleDateString()}
            </p>
          </div>

          {/* Report body */}
          <div className="p-6 text-sm leading-relaxed text-near-black whitespace-pre-wrap">
            {report}
          </div>

          {/* Disclaimer */}
          <div className="px-6 pb-4">
            <p className="text-xs text-neutral-400 border-t border-neutral-200 pt-3">
              This summary was generated by Purridiction using AI. It is not a medical diagnosis. Please share with your vet for professional evaluation.
            </p>
          </div>

          {/* Copy button */}
          <div className="border-t-2 border-near-black p-4 space-y-2">
            <button onClick={handleCopy}
              className="w-full bg-hot-pink text-white font-black py-3 border-2 border-near-black hover:bg-pink-700 uppercase shadow-[4px_4px_0px_#1A1A2E] hover:shadow-[2px_2px_0px_#1A1A2E] hover:translate-x-[2px] hover:translate-y-[2px] transition-all">
              {copied ? "COPIED!" : "Copy Summary to Share with Vet"}
            </button>
            <button onClick={() => setReport(null)}
              className="w-full bg-white text-near-black font-black py-2 border-2 border-near-black hover:bg-neutral-100 text-sm uppercase">
              Regenerate
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
