import { useState } from "react";
import { callGemini } from "../lib/gemini";
import { buildVetReportPrompt } from "../lib/vetReport";

export default function VetReport({ cat, predictions, healthLogs }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const hasEnoughData = predictions.length > 0 || healthLogs.length > 0;
  if (!hasEnoughData) {
    return (
      <div className="border-4 border-dashed border-[#3D3480] p-4 text-center rotate-[-1deg]">
        <p className="font-impact text-lg text-[#3D3480] uppercase">Vet Report Unavailable</p>
        <p className="font-mono text-[10px] text-[#3D3480]/60 mt-1">Log at least one health entry or prediction first.</p>
      </div>
    );
  }

  const handleGenerate = async () => {
    setLoading(true); setError(null);
    try {
      const prompt = buildVetReportPrompt(cat, predictions, healthLogs);
      const narration = await callGemini(prompt);
      setReport(narration);
    } catch { setError("Failed to generate. Try again."); } finally { setLoading(false); }
  };

  const fullText = report ? `VET VISIT SUMMARY\nCat: ${cat.name} (${cat.age_category})\nGenerated by Purridiction\n\n${report}` : "";
  const handleCopy = () => { navigator.clipboard.writeText(fullText); setCopied(true); setTimeout(() => setCopied(false), 2000); };

  return (
    <div className="space-y-4">
      <h3 className="font-impact text-2xl text-[#3D3480] uppercase rotate-[-1deg] inline-block"
        style={{ textShadow: '2px 2px 0 rgba(61,52,128,0.2)' }}>Vet Visit Prep</h3>

      {!report && (
        <button onClick={handleGenerate} disabled={loading}
          className="w-full bg-[#3D3480] text-white font-impact text-xl py-4 border-4 border-[#1A1A2E] uppercase rotate-[1deg] hover:rotate-[0deg] transition-transform disabled:opacity-50"
          style={{ boxShadow: '8px 8px 0 #FF3366' }}>
          {loading ? "GENERATING..." : "Generate 7-Day Summary 🏥"}
        </button>
      )}
      {error && <p className="text-[#FF3366] font-black text-sm border-2 border-[#FF3366] p-2 text-center">{error}</p>}

      {report && (
        <div className="border-4 border-[#1A1A2E] bg-white rotate-[-1deg]" style={{ boxShadow: '10px 10px 0 #FF3366' }}>
          <div className="bg-[#1A1A2E] text-white p-4 border-b-4 border-[#FFD700]">
            <p className="font-mono text-[10px] tracking-widest mb-1 text-[#00CFFF]">PURRIDICTION // VET VISIT PREP</p>
            <p className="font-impact text-2xl text-[#FFD700]">{cat.name.toUpperCase()}</p>
            <p className="font-mono text-[10px] text-purple-300 mt-1">7-Day Summary // {new Date().toLocaleDateString()}</p>
          </div>
          <div className="p-6 text-sm leading-relaxed text-[#1A1A2E] whitespace-pre-wrap font-body">{report}</div>
          <div className="px-6 pb-4">
            <p className="font-mono text-[9px] text-[#3D3480]/40 border-t border-[#1A1A2E]/10 pt-3">AI-generated. Not a medical diagnosis. Share with your vet for professional evaluation.</p>
          </div>
          <div className="border-t-2 border-[#1A1A2E] p-4 space-y-2">
            <button onClick={handleCopy}
              className="w-full bg-[#FF3366] text-white font-impact py-3 border-2 border-[#1A1A2E] uppercase hover:scale-[1.02] transition-transform"
              style={{ boxShadow: '4px 4px 0 #1A1A2E' }}>{copied ? "COPIED!" : "Copy for Vet"}</button>
            <button onClick={() => setReport(null)}
              className="w-full bg-white text-[#1A1A2E] font-black py-2 border-2 border-[#1A1A2E] text-sm uppercase hover:bg-[#FFFBF0]">Regenerate</button>
          </div>
        </div>
      )}
    </div>
  );
}
