import { useState } from "react";
import { supabase } from "../lib/supabase";
import { buildVetReportPrompt } from "../lib/vetReport";

export default function VetReport({ cat, predictions, healthLogs }) {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const hasEnoughData = predictions.length > 0 || healthLogs.length > 0;

  if (!hasEnoughData) {
    return (
      <div className="border-4 border-dashed border-[#3D3480] p-4 text-center rotate-[-1deg]">
        <p className="font-impact text-lg text-[#3D3480] uppercase">Vet Report Unavailable</p>
        <p className="font-mono text-xs text-[#3D3480]/60 mt-1">Log at least one health entry or prediction to generate a vet report.</p>
      </div>
    );
  }

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const prompt = buildVetReportPrompt(cat, predictions, healthLogs);
      const { data, error: fnError } = await supabase.functions.invoke("gemini-proxy", { body: { prompt } });
      if (fnError) throw fnError;
      setReport(data.narration);
    } catch {
      setError("Failed to generate report. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const fullText = report ? `VET VISIT SUMMARY\nCat: ${cat.name} (${cat.age_category})\nGenerated by Purridiction\n\n${report}` : "";

  const handleCopy = () => {
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      <h3 className="font-impact text-2xl text-[#3D3480] uppercase rotate-[-1deg] inline-block">Vet Visit Prep</h3>

      {!report && (
        <button onClick={handleGenerate} disabled={loading}
          className="w-full bg-[#3D3480] text-white font-impact text-xl py-4 border-4 border-[#1A1A2E] shadow-[6px_6px_0px_#00CFFF] uppercase hover:scale-[1.02] transition-transform disabled:opacity-50 rotate-[1deg]">
          {loading ? "GENERATING SUMMARY..." : "Generate 7-Day Summary for Vet 🏥"}
        </button>
      )}

      {error && <p className="text-[#FF3366] text-sm font-black border-2 border-[#FF3366] p-2 text-center">{error}</p>}

      {report && (
        <div className="border-4 border-[#1A1A2E] bg-white shadow-[8px_8px_0px_#3D3480]">
          {/* Header */}
          <div className="bg-[#3D3480] text-white p-4 border-b-4 border-[#1A1A2E]">
            <p className="font-mono text-xs tracking-widest mb-1">PURRIDICTION // VET VISIT PREP</p>
            <p className="font-impact text-2xl text-[#FFD700]">{cat.name.toUpperCase()}</p>
            <p className="font-mono text-xs text-purple-300 mt-1">7-Day Summary // Generated {new Date().toLocaleDateString()}</p>
          </div>

          {/* Body */}
          <div className="p-6 text-sm leading-relaxed text-[#1A1A2E] whitespace-pre-wrap font-body">
            {report}
          </div>

          {/* Disclaimer */}
          <div className="px-6 pb-4">
            <p className="font-mono text-[10px] text-[#3D3480]/50 border-t border-[#1A1A2E]/20 pt-3">
              This summary was generated by Purridiction using AI. It is not a medical diagnosis. Please share with your vet for professional evaluation.
            </p>
          </div>

          {/* Actions */}
          <div className="border-t-2 border-[#1A1A2E] p-4 space-y-2">
            <button onClick={handleCopy}
              className="w-full bg-[#FF3366] text-white font-black py-3 border-2 border-[#1A1A2E] shadow-[4px_4px_0px_#1A1A2E] uppercase hover:scale-[1.02] transition-transform">
              {copied ? "COPIED!" : "Copy Summary to Share with Vet"}
            </button>
            <button onClick={() => setReport(null)}
              className="w-full bg-white text-[#1A1A2E] font-black py-2 border-2 border-[#1A1A2E] text-sm uppercase hover:bg-[#FFFBF0]">
              Regenerate
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
